name: DeathPrison
main: com.example.deathprison.DeathPrison
version: 1.0
api-version: 1.20
commands:
  setprison:
    description: Set the prison location
    usage: /setprison
permissions:
  prison.set:
    description: Allows setting the prison location
    default: op
